services:

  elasticsearch-container:
    container_name: elasticsearch-container
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_IMAGE_TAG}
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=${ELASTIC_SECURITY}
      - "ES_JAVA_OPTS=${ES_JAVA_OPTS}"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - ${ELASTIC_PORT}:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -u elastic:'${ELASTIC_PASSWORD}' --silent --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      retries: 3
    networks:
      - elk-network
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        /usr/local/bin/docker-entrypoint.sh &
        sleep 30 && \
        elasticsearch-users useradd "${KIBANA_USER}" -p "${KIBANA_PASSWORD}" -r kibana_system && \
        wait
      - |
        /usr/local/bin/docker-entrypoint.sh &
        sleep 30 && \
        elasticsearch-users useradd "${LOGSTASH_USER}" -p "${LOGSTASH_PASSWORD}" -r logstash_system && \
        wait

  kibana-container:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:${KIBANA_IMAGE_TAG}
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-container:${ELASTIC_PORT}
      - ELASTICSEARCH_USERNAME=${KIBANA_USER}
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    ports:
      - ${KIBANA_PORT}:5601
    depends_on:
      elasticsearch-container:
        condition: service_healthy
    networks:
      - elk-network

  
  logstash-container:
    container_name: logstash-container
    image: docker.elastic.co/logstash/logstash:${LOGSTASH_IMAGE_TAG}
    volumes:
      - ./pipeline/pipeline.conf:/usr/share/logstash/pipeline/pipeline.conf
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch-container:${ELASTIC_PORT}
      - ELASTICSEARCH_USERNAME=${LOGSTASH_USER}
      - ELASTICSEARCH_PASSWORD=${LOGSTASH_PASSWORD}
      - xpack.monitoring.enabled=true
    ports:
      - ${LOGSTASH_PORT}:5044
      - 9600:9600
    depends_on:
      elasticsearch-container:
        condition: service_healthy
    networks:
      - elk-network
  
volumes:
  elasticsearch-data:
    name: elasticsearch-data
    driver: local

networks:
  elk-network:
    driver: bridge
    name: elk-network