services:
  prometheus:
    container_name: prometheus-container
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-volume:/prometheus
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - prometheus

volumes:
  prometheus-volume:
    name: prometheus-data
    driver: local

networks:
  prometheus:
    driver: bridge
    name: prometheus
