services:
  api-container:
    container_name: ${API_NAME}-container
    restart: unless-stopped
    build:
      context: ..
      target: ${NODE_ENV}
      dockerfile: ./.docker/Dockerfile
      args:
        NODE_IMAGE_TAG: "${NODE_IMAGE_TAG}"
        NODE_ENV: "${NODE_ENV}"
    image: ${API_NAME}-${NODE_ENV_MIN}:${TAG_VERSION}
    command: npm run ${START_COMMAND}
    ports:
      - "${API_PORT}:3000"
      - "9229:9229" #debug port
    environment:
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ../api:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - dev-network

networks:
  dev-network:
    external: true