global:
  scrape_interval: 15s  # Intervalo de recolección de métricas (por defecto 1m)
  evaluation_interval: 15s  # Frecuencia de evaluación de reglas

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]