services:
  tensorflow-container:
    container_name: tensorflow-container
    image: tensorflow/tensorflow:${TENSORFLOW_IMAGE_TAG}  # Imagen oficial de TensorFlow con soporte para GPU y Jupyter
    restart: unless-stopped
    ports:
      - "${JUPYTER_NOTEBOOK_PORT}:8888"  # Puerto para Jupyter Notebook
      - "${TENSORFLOW_PORT}:6006"  # Puerto para TensorBoard
    volumes:
      - ./notebooks:/tf/notebooks  # Monta un directorio local para los notebooks
      - ./data:/tf/data  # Monta un directorio local para los datos
      - ./logs:/tf/logs  # Monta un directorio local para los logs de TensorBoard
    environment:
      JUPYTER_TOKEN: /run/secrets/tensorflow-container-jupyter-token
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # Habilita el soporte para GPU (opcional, solo si tienes una GPU compatible)    
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:8888/ || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - dev-network

secrets:
  tensorflow-container-jupyter-token:
    file: ./secrets/jupyter-token.txt

networks:
  dev-network:
    external: true